In [54]:
import pandas as pd
import numpy as np

**1:** Create a NumPy array from a python list


In [55]:
a = [1,2,3]
np.array(a)

array([1, 2, 3])

In [56]:
type(np.array(a)) # type of an array

numpy.ndarray

In [57]:
b = [[1,2,3],[4,5,6]]          #2D array
np.array(b, dtype=np.float32)           

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [58]:
type(np.array(b))

numpy.ndarray

**2:** Create a NumPy array of Zeros

In [59]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,3))   # for multidimensional array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones((4,4))   # a NumPy array of Ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
np.eye(3) # an Identity Numpy Array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.arange(10,100,2)  #an equally spaced Numpy Array with a specific step
# np.arange(start , stop, step) 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [64]:
# Generate values from start=5to stop=11 with step=1:
np.arange(5,11,2)

array([5, 7, 9])

In [65]:
np.linspace(10,100,20)  #  Create an equally spaced Numpy Array with a specific array size

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])



Generate a random numpy array



In [66]:
np.random.randint(10,25,5)  # generate a random array of integers
# np.random.randint(low,high,size)

array([17, 24, 14, 22, 10])

In [67]:
np.random.random(10)  #  generate random float samples

array([0.02277792, 0.86359183, 0.5356564 , 0.19703331, 0.98683473,
       0.11752203, 0.52596449, 0.0872552 , 0.5149489 , 0.53957169])

**8:** *Generate NumPy Array from a Pandas Series*


In [68]:
s = pd.Series([1,2,3,4], name = "col")
#np.array(s)
np.asarray(s)

array([1, 2, 3, 4])

***NumPy Array Manipulation Methods***

---

In [69]:
# 1: Shape of the NumPy Array
a = np.ones((5, 6))
np.shape(a)
#a.shape

(5, 6)

In [70]:
b = np.arange(12)   # Reshape the NumPy Array
b.reshape((6,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [71]:
a = np.arange(20).reshape((10, 2))   # Transpose the NumPy Array
#a.transpose()
a.T

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [72]:
# Concatenate multiple NumPy arrays to form one NumPy Array
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[7,8]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
np.concatenate((a.T, b), axis=0)

array([[1, 3],
       [2, 4],
       [5, 6],
       [7, 8]])

In [74]:
np.concatenate((a, b.T), axis=0)

array([[1, 2],
       [3, 4],
       [5, 7],
       [6, 8]])

In [75]:
np.concatenate((a, b), axis=1)  ## Concatenate Column-wise

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [76]:
np.concatenate((a, b), axis=None) # Concatenate to generate a flat NumPy Array

array([1, 2, 3, 4, 5, 6, 7, 8])

axis=0 is same as np.vstack()

axis=1 is same as np.hstack()




In [77]:
a.flatten()  #  Flatten NumPy Array

array([1, 2, 3, 4])

In [78]:
# Unique Elements of a NumPy Array
a = np.array([[1, 2], [2, 3],[3,4]])
np.unique(a)

array([1, 2, 3, 4])

In [79]:
## Return Unique Rows

a = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [81]:
## Return Unique Columns
a = np.array([[1, 1, 3], [2, 1, 3], [7, 5, 4]])
np.unique(a,axis=0)

array([[1, 1, 3],
       [2, 1, 3],
       [7, 5, 4]])

In [82]:
# Squeeze a NumPy Array
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [83]:
np.squeeze(x).shape

(3,)

In [84]:
# Transform NumPy Array to Python List
a = np.array([[1, 10, 3], [9, 1, 3], [1, 1, 4]])
a.tolist()

[[1, 10, 3], [9, 1, 3], [1, 1, 4]]

***Mathematical Operations on NumPy Arrays***

In [85]:
a = np.array([1,2,3])
print("Trigonometric Sine   :", np.sin(a))
print("Trigonometric Cosine :", np.cos(a))
print("Trigonometric Tangent:", np.tan(a))

Trigonometric Sine   : [0.84147098 0.90929743 0.14112001]
Trigonometric Cosine : [ 0.54030231 -0.41614684 -0.9899925 ]
Trigonometric Tangent: [ 1.55740772 -2.18503986 -0.14254654]


In [86]:
# Round to given number of decimals using the np.round_() method:
a = np.linspace(1, 2, 5)
np.round_(a, 2) # 2 decimal places

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [87]:
# Return the element-wise floor using the np.floor() method.
np.floor(a)

array([1., 1., 1., 1., 2.])

In [88]:
# Return the element-wise ceiling using the np.ceil() method.
np.ceil(a)

array([1., 2., 2., 2., 2.])

In [89]:
# Round to nearest integer using the np.rint() method.
np.rint(a)

array([1., 1., 2., 2., 2.])

In [90]:
# Calculate the element-wise exponential using the np.exp() method.
# Calculate the element-wise natural logarithm using the np.log() method.

In [91]:
# Exponents and logarithms
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [92]:
np.exp(a).round(2)

array([  2.72,   7.39,  20.09,  54.6 , 148.41])

In [93]:
np.log(a).round(2)

array([0.  , 0.69, 1.1 , 1.39, 1.61])

In [ ]:
# Sum and Product
# Use the np.sum() method to calculate the sum of array elements
# Use the np.prod() method to calculate the product of array elements:

In [94]:
a = np.array([[1, 2], [3, 4]])
np.sum(a)

10

In [95]:
np.sum(a, axis = 0)

array([4, 6])

In [96]:
np.sum(a, axis = 1)

array([3, 7])

In [97]:
np.prod(a)

24

In [98]:
 np.prod(a, axis = 0)

array([3, 8])

In [99]:
 np.prod(a, axis = 1)

array([ 2, 12])

In [100]:
# Square Root
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

***Matrix and Vector Operations***

In [101]:
# 1: Dot Product
# If you want to calculate the dot product of two NumPy arrays, use the np.dot() method:

In [102]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])
np.dot(a, b)

array([[3, 3],
       [7, 7]])

In [103]:
# 2: Matrix Product
# To calculate the matrix product of two NumPy arrays, use thenp.matmul() or the @ operator in Python:

In [104]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])


In [105]:
np.matmul(a, b)

array([[3, 3],
       [7, 7]])

In [106]:
a@b

array([[3, 3],
       [7, 7]])

In [ ]:
# 3/n: Vector Norm
# Vector norms represent a set of functions used to measure a vector’s length
# Use the np.linalg.norm() method to find the matrix or vector norm:

In [108]:
a = np.arange(-4, 5)
a

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [109]:
np.linalg.norm(a) ## L2 Norm

7.745966692414834

In [110]:
np.linalg.norm(a, 1) ## L1 Norm

20.0

***Sorting Methods***

In [111]:
# To sort the array in-place, use the ndarray.sort() method.
a = np.array([[1,4],[3,1]])
a

array([[1, 4],
       [3, 1]])

In [112]:
np.sort(a, axis=None)

array([1, 1, 3, 4])

In [113]:
np.sort(a, axis=0)

array([[1, 1],
       [3, 4]])

In [ ]:
# Order of Indices in a Sorted NumPy Array

In [114]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

***Searching Methods***

In [115]:
d = np.random.randint(1, 20, 10).reshape(2,5)
d

array([[11, 16, 10,  8,  4],
       [11, 17,  7, 19, 18]])

In [116]:
np.argmax(d)

8

In [117]:
np.argmax(d, axis=0)

array([0, 1, 0, 1, 1])

In [118]:
np.argmax(d, axis=1)

array([1, 3])

In [ ]:
# Indices corresponding to Minimum Values

In [119]:
 a = np.random.randint(1, 20, 10).reshape(2,5)
 a

array([[ 8,  6, 10, 15, 10],
       [10, 15, 18,  1, 11]])

In [120]:
np.argmin(a)

8

In [121]:
np.argmin(a, axis=0)

array([0, 0, 0, 1, 0])

In [122]:
np.argmin(a, axis=1)

array([1, 3])

In [ ]:
# 3: Search based on condition
# If you want to select between two arrays based on a condition, use the np.where() method as shown below:

In [123]:
a = np.random.randint(-10, 10, 10)
a

array([ -2,   0,  -3, -10,   8,   9,  -3,   1,   4,  -5])

In [124]:
np.where(a < 0, 0, a)

array([0, 0, 0, 0, 8, 9, 0, 1, 4, 0])

In [ ]:
# 4/n: Indices of Non-Zero Elements
# To determine the indices of non-zero elements in a NumPy Array, use the np.nonzero() method:

In [125]:
a = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
np.nonzero(a)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

***Statistical Methods***

In [ ]:
# 1: Mean
# To find the mean of the values in a numpy array along an axis, use the np.mean() method as demonstrated below:

In [126]:
a = np.array([[1, 2], [3, 4]])

In [127]:
np.mean(a)

2.5

In [128]:
np.mean(a, axis = 1)

array([1.5, 3.5])

In [129]:
np.mean(a, axis = 0)

array([2., 3.])

In [ ]:
# 2/n: Median
# To compute the median of a numpy array, use the np.median() method.

In [130]:
a = np.array([[1, 2], [3, 4]])

In [131]:
np.median(a)

2.5

In [132]:
np.median(a, axis = 1) ## along the row axis

array([1.5, 3.5])

In [133]:
np.median(a, axis = 0) ## along the column axis

array([2., 3.])

In [ ]:
# 3/n: Standard Deviation
# To compute the standard deviation of a numpy array along a specified array, use the np.std() method.

In [134]:
a = np.array([[1, 2], [3, 4]])
a


array([[1, 2],
       [3, 4]])

In [135]:
np.std(a)

1.118033988749895

In [136]:
np.std(a, axis = 1) ## along the row axis

array([0.5, 0.5])

In [137]:
np.std(a, axis = 0) ## along the column axis

array([1., 1.])